[project]
name = "ah_swapface"
version = "1.0.1"
description = "Face swapping plugin using insightface"
dependencies = [
    "onnxruntime",
    "torch",
    "opencv-python",
    "pillow",
    "numpy",
    "nanoid"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
